In [1]:
import time

from AntColonyOptimization import AntColonyOptimization
from GeneticAlgorithm import GeneticAlgorithm
from Maze import Maze
from PathSpecification import PathSpecification
from TSPData import TSPData
import numpy as np

### Part 1: The Travelling Robot Problem

In [2]:
# Please keep your parameters for the Genetic Algorithm easily changeable here
population_size = 200
generations = 200
elite_size = 0.1
mutation_rate = 0.01
persist_file = "./../data/optimal_tsp"

# Setup optimization
tsp_data = TSPData.read_from_file(persist_file)
ga = GeneticAlgorithm(generations, population_size, elite_size, mutation_rate)

# Print distance matrix without aco
print(np.array(tsp_data.distances))

# Run optimzation and write to file
solution = ga.solve_tsp(tsp_data)
tsp_data.write_action_file(solution[0], "./../data/tsp_solution.txt")

[[  0  69 698 240 132 527 156 459 374 409 599 428 483 167 425 221 691 465]
 [ 69   0 647 189  81 476 105 408 323 358 548 377 432 116 374 170 640 414]
 [698 647   0 472 568 185 596 345 324 289 105 270 237 531 283 491 183 351]
 [240 189 472   0 110 301 138 233 148 183 373 202 257  73 199  19 465 239]
 [132  81 568 110   0 397  36 329 244 279 469 298 353  37 295  91 561 335]
 [527 476 185 301 397   0 425 174 153 118  86  99  66 360 112 320 178 180]
 [156 105 596 138  36 425   0 357 272 307 497 326 381  65 323 119 589 363]
 [459 408 345 233 329 174 357   0  85  56 246  75 130 292  72 252 338  26]
 [374 323 324 148 244 153 272  85   0  35 225  54 109 207  51 167 317  91]
 [409 358 289 183 279 118 307  56  35   0 190  19  74 242  16 202 282  62]
 [599 548 105 373 469  86 497 246 225 190   0 171 138 432 184 392  98 252]
 [428 377 270 202 298  99 326  75  54  19 171   0  55 261  13 221 263  81]
 [483 432 237 257 353  66 381 130 109  74 138  55   0 316  68 276 230 136]
 [167 116 531  73  37 360

### Part 2: Path Finding Through Ant Colony Optimization

In [4]:
# Please keep your parameters for the ACO easily changeable here
gen = 30
no_gen = 40
q = 4000
evap = 0.4

# Construct the optimization objects
maze = Maze.create_maze("./../data/hard_maze.txt")
spec = PathSpecification.read_coordinates("./../data/hard_coordinates.txt")
aco = AntColonyOptimization(maze, gen, no_gen, q, evap)

# Save starting time
start_time = int(round(time.time() * 1000))

# Run optimization
shortest_route = aco.find_shortest_route(spec)

# Print time taken
print("Time taken: " + str((int(round(time.time() * 1000)) - start_time) / 1000.0))

# Save solution
shortest_route.write_to_file("./../data/hard_solution.txt")

# Print route size
print("Route size: " + str(shortest_route.size()))

Ready reading maze file ./../data/hard_maze.txt
Found route of length 1143
Found route of length 1421
Found route of length 1259
Found route of length 1291
Found route of length 1123
Found route of length 1257
Found route of length 1333
Found route of length 1401
Found route of length 1071
Found route of length 1101
Found route of length 1107
Found route of length 1257
Found route of length 1333
Found route of length 1167
Found route of length 1101
Found route of length 1057
Found route of length 1251
Found route of length 1109
Found route of length 1039
Found route of length 1161
Found route of length 1141
Found route of length 1299
Found route of length 1293
Found route of length 1249
Found route of length 1097
Found route of length 1237
Found route of length 1123
Found route of length 1185
Found route of length 1109
Found route of length 1059
Found route of length 1175
Found route of length 1093
Found route of length 1209
Found route of length 1137
Found route of length 1157
Found r

### Synthesis

In [3]:
# Please keep your parameters for the synthesis part easily changeable here
gen = 1
no_gen = 1
q = 4000
evap = 0.5
elite_size = 0.1
mutation_rate = 0.01

persist_file = "./../data/my_tsp.txt"
tsp_path = "./../data/tsp_products.txt"
coordinates = "./../data/hard_coordinates.txt"

# Construct optimization
maze = Maze.create_maze("./../data/hard_maze.txt")
tsp_data = TSPData.read_specification(coordinates, tsp_path)
aco = AntColonyOptimization(maze, gen, no_gen, q, evap)

# Run optimization and write to file
tsp_data.calculate_routes(aco)
tsp_data.write_to_file(persist_file)

# Print distance matrix after aco
print(np.array(tsp_data.distances))

# Read from file and print
tsp_data2 = TSPData.read_from_file(persist_file)
print(tsp_data == tsp_data2)

# Solve TSP using your own paths file
ga = GeneticAlgorithm(generations, population_size, elite_size, mutation_rate)
solution = ga.solve_tsp(tsp_data2)
tsp_data2.write_action_file(solution[0], "./../data/tsp_solution_with_aco.txt")

Ready reading maze file ./../data/hard_maze.txt
[[   0  111 1050  358  266 1101  200  957  488  761 1159 1056  801  215
   783  463  955  771]
 [ 121    0 1087  261  123  774  177  510  517  546  902  795  806  148
   710  254  994  622]
 [1186 1153    0  844 1072  215 1116  537  742  447  107  326  301  857
   351  803  183  797]
 [ 362  267  842    0  212  425  294  811  154  307  915  498  505   75
   445   27  885  651]
 [ 216  165  732  246    0  751   76  739  336  577 1043  392  575  111
   469  203  725  933]
 [ 815  850  209  737  635    0  735  540  489  172  114  193   94  586
   182  572  224  614]
 [ 216  215  884  232   80  751    0  413  420  693  889  608  711   77
   423  261  797  557]
 [ 717  788  445  439  487  630  581    0  143   82  632  219  220  664
   242  620  516   42]
 [ 486  473  690  190  390  531  310  437    0   73  491  418  341  219
   163  213  793  197]
 [ 857  928  419  709  741  420  595  112  387    0  494  379  448  370
   148  562  382  146]
 [